FROM python:3.12.7-slim-bullseye
RUN mkdir /app
WORKDIR /app
COPY ./discord-bots/oa-bot-py /app
COPY ./oasst-shared/oasst_shared /app/oasst_shared
RUN pip install -r requirements.txt
CMD ["python","-m","bot"]
